config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#index'
  post 'edit', to: 'pages#edit', as: 'edit'
  post 'create', to: 'pages#create', as: 'create'
  delete 'delete/:id', to: 'pages#delete', as: 'delete'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/video.rb
class Video < ApplicationRecord
  has_one_attached :file

  def self.concat_videos(files, resolutions)
    unless resolutions.blank?
      w = FFMPEG::Movie.new(files[resolutions[0].to_i - 1].path.to_s).width
      h = FFMPEG::Movie.new(files[resolutions[0].to_i - 1].path.to_s).height
    else
      w = FFMPEG::Movie.new(files[0].path.to_s).width
      h = FFMPEG::Movie.new(files[0].path.to_s).height
    end

    code = rand(36**15).to_s(36)
    ext = File.extname(files[0].original_filename)
    blobs = []
    files.each_with_index do |file, i|
      ext = File.extname(file.original_filename)
      blob = ActiveStorage::Blob.create_after_upload!(io: file, filename: "#{code}-#{i}#{ext}")
      blobs << blob
    end

    paths = []
    blobs.each_with_index do |blob, i|
      str = "ffmpeg "
      blob_path = ActiveStorage::Blob.service.send(:path_for, blob.key)
      str += "-i #{blob_path} -vf 'scale=#{w}:#{h}:force_original_aspect_ratio=decrease,pad=#{w}:#{h}:x=(#{w}-iw)/2:y=(#{h}-ih)/2:color=black,setsar=1:1' -vb 20M -y #{code}#{ext}"
      system str
      blob.purge

      if (FFMPEG::Movie.new("#{code}#{ext}").audio_stream.blank?)
        str = "ffmpeg -f lavfi -i anullsrc=channel_layout=stereo:sample_rate=44100 -i #{code}#{ext} -c:v copy -c:a aac -shortest #{code}-#{i}#{ext}"
      else
        str = "ffmpeg -i #{code}#{ext} #{code}-#{i}#{ext}"
      end
      system str

      paths << "#{code}-#{i}#{ext}"
    end

    str = "ffmpeg "
    paths.each do |path|
      str += "-i #{path} "
    end

    str += "-filter_complex '"
    paths.count.times do |i|
      str += "[#{i}:v][#{i}:a]"
    end
    str += "concat=n=#{paths.count}:v=1:a=1 [v] [a]' -map '[v]' -map '[a]' -vb 20M -y #{code}#{ext}"
    system str

    path = Rails.root.join("#{code}#{ext}")
    file = File.open(path, "rb")
    blob = ActiveStorage::Blob.create_after_upload!(io: file, filename: "#{code}#{ext}")
    File.delete(path)
    paths.each { |path| File.delete(path) }

    blob
  end

  def self.process_video(name, format, blob_key, width, height, starting, ending) # more options to come
    tmp_blob = ActiveStorage::Blob.find_by(key: blob_key)
    tmp_path = ActiveStorage::Blob.service.send(:path_for, blob_key)

    unless starting.blank?
      str = "ffmpeg "
      paths_to_delete = []

      starting.count.times.each do |i|
        path = "#{blob_key}-#{i}#{format}"
        system "ffmpeg -i #{tmp_path} -ss #{starting[i]} -to #{ending[i]} -vb 20M #{path}"
        str += "-i #{path} "
        paths_to_delete << path
      end

      str += "-filter_complex '"
      starting.count.times do |i|
        str += "[#{i}:v][#{i}:a]"
      end
      str += "concat=n=#{starting.count}:v=1:a=1 [v] [a]' -map '[v]' -map '[a]' -s #{width}x#{height} -vb 20M #{name}#{format}"
      system str

      paths_to_delete.each do |path|
        File.delete(path)
      end
    else
      str = "ffmpeg -i #{tmp_path} -s #{width}x#{height} -vb 20M #{name}#{format}"
      system str
    end

    tmp_blob.purge

    output_path = Rails.root.join("#{name}#{format}")
    file = File.open(output_path, "rb")
    blob = ActiveStorage::Blob.create_after_upload!(io: file, filename: "#{name}#{format}")

    File.delete(output_path)

    blob
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  rescue_from Exception, with: :exception

  def index
    @videos = Video.all
  end

  def edit
    @concat_video_blob = Video.concat_videos(params[:files], params[:resolutions])
    @ffprobe_json = Ffprober::Parser.from_file(ActiveStorage::Blob.service.send(:path_for, @concat_video_blob.key)).json
  end

  def create
    blob = Video.process_video(params[:name], params[:format], params[:file], params[:width], params[:height], params[:starting] || [], params[:ending] || [])

    video = Video.new(name: params[:name])
    video.file.attach(blob)
    video.save!

    redirect_to root_path
  end

  def delete
    video = Video.find(params[:id])
    video.file.purge
    video.destroy

    redirect_to root_path
  end

  private
  def exception
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Videotest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/edit.html.slim
h1 Video Editing
hr

= video_tag rails_blob_path(@concat_video_blob), controls: true
br
h5 Duration : #{@ffprobe_json[:format][:duration]}
br
= button_tag 'get current timestamp', type: :button, id: 'get-timestamp'
= text_field_tag 'name', '', readonly: true, id: 'get-timestamp-field'
hr
= form_tag create_path, method: :post do
  = label_tag 'name'
  = text_field_tag 'name'
  br
  = label_tag 'format'
  = text_field_tag 'format', '', placeholder: File.extname(@concat_video_blob.filename.to_s)
  br
  = label_tag 'width'
  = text_field_tag 'width', '', placeholder: @ffprobe_json[:streams][0][:coded_width]
  br
  = label_tag 'height'
  = text_field_tag 'height', '', placeholder: @ffprobe_json[:streams][0][:coded_height]
  br
  = label_tag 'cut'
  = button_tag 'add cutting field', type: :button, id: 'add-cut-button'
  = button_tag 'clear cutting fields', type: :button, id: 'clear-cut-button'
  .cuts-field
    .cut-field-class
      = text_field_tag 'starting[]', '', placeholder: 'hh:mm:ss.0000'
      |  - 
      = text_field_tag 'ending[]', '', placeholder: 'hh:mm:ss.0000'
  br
  = hidden_field_tag 'file', @concat_video_blob.key
  = submit_tag 'save'

h3 Ffprobe
h4 Streams
- @ffprobe_json[:streams].each do |stream|
  table style="border-collapse: collapse;"
    - stream.keys.each do |k|
        tr
          th = k
          td = stream[k]
  br
h4 Format
table style="border-collapse: collapse;"
  - @ffprobe_json[:format].each do |k, v|
    tr
      th = k
      td = v
br
h4 Chapters
p = @ffprobe_json[:chapters]


javascript:
  $("tr, table").prop("border", "1px solid black")

  function GetTimestampStringFormat(time){
    let miliseconds = time.toString().split(".")[1] || ("")
    let value = new Date(time * 1000).toISOString().substr(11, 8) + "." + miliseconds
    return value
  }

  let cut_field = $(".cut-field-class").html()
  $(".cuts-field").html("")

  $("#add-cut-button").click(function(){
    $(".cuts-field").append(
      "<br>" + ($(".cut-field-class").length + 1) + ")<div class='cut-field-class'>" + cut_field + "</div>"
      )
  })

  $("#clear-cut-button").click(function(){
    $(".cuts-field").html("")
  })

  $("#get-timestamp").click(function(){
    $("#get-timestamp-field").val(GetTimestampStringFormat($("video")[0].currentTime))
  })

app/views/pages/index.html.slim
h1 Video Uploading
hr
| *tick the checkbox to select resolution, if there aren't any checkboxes ticked, the first file's resolution will be selected
= form_tag edit_path, method: :post, multipart: true do
  .files-field
    .file-field-class
      = file_field_tag 'files[]'
  br
  = button_tag 'add file', type: 'button', id: 'add-file-button'
  = button_tag 'clear files', type: 'button', id: 'clear-file-button'
  br
  = submit_tag 'upload'
end

hr
h2 Video list
- @videos.each do |video|
  .video
    h5
      = video.name
    h5
      = link_to 'delete', delete_path(video), method: :delete
    h5
      a href="#{url_for(video.file)}" download="#{video.file}" download
    = video_tag rails_blob_path(video.file), controls: true
hr

javascript:
  let file_field = $(".file-field-class").html()
  $(".files-field").html("")

  $("#add-file-button").click(function(){
    $(".files-field").append(
      "<br>" + ($(".file-field-class").length + 1) + ")<div class='file-field-class'>" + file_field + "<input type='checkbox' value='true' onchange='setOtherFalse(" + ($(".file-field-class").length) + ")' name='resolutions[" + ($(".file-field-class").length + 1) + "]'></div>"
      )
  })

  $("#clear-file-button").click(function(){
    $(".files-field").html("")
  })

  function setOtherFalse(index)
  {
    for(var i = 0; i < $("input[type='checkbox']").length; i++){
      if(i != index) $("input[type='checkbox']")[i].checked = false;
    }
  }